DROP TABLE IF EXISTS fact_lap CASCADE;
DROP TABLE IF EXISTS fact_result CASCADE;
DROP TABLE IF EXISTS pipeline_run CASCADE;
DROP TABLE IF EXISTS dim_constructor CASCADE;
DROP TABLE IF EXISTS dim_driver CASCADE;
DROP TABLE IF EXISTS dim_event CASCADE;